application: multi-factor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /
  script: main.app
- url: /tokens
  script: main.app
  secure: always
- url: /signup
  script: main.app
  secure: always
- url: /api/.*
  script: api.app
  login: required
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"
